idf_component_register(
    SRCS
        "app_main.c"
        "Transport/MCP2515Transport.c"
        "Core/PIDTable.c"
        "Data/Mode01Data.c"
        "Decoder/Decoder.c"
        "Core/OBD2.c"
        "BLE/ELM327_BLE.c"
    INCLUDE_DIRS
        "."
        "Core"
        "BLE"
        "Transport"
        "Decoder"
        "Data"
    REQUIRES
        bt
        nvs_flash
        esp_driver_spi
        esp_timer
)
